feat: первый коммит по тз13
BerezinYaroslav/java-shareit pull request #1
Opened 2023-05-25 23:52 UTC by BerezinYaroslav

2023-05-26 13:32 UTC, TomattmanYandex requested changes
Привет отличная работа, есть пара моментов на исправление

2023-05-26 13:32 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/booking/model/Booking.java
> +package ru.practicum.shareit.booking.model;
при построении пакетов как в текущем проекте, основной проект обычно не разбивают по функционалу,
т.е. есть пакет booking и в нем все что касается бронирований, без дополнительных пакетов

2023-05-26 13:32 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/booking/model/Booking.java
> +//enum Status {
закомментированный код не допускается

2023-05-26 13:32 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/item/ItemMapper.java
> +    public static ItemDto toItemDto(Item item) {
если назвать методы toDto и toObject то все мапперы будут иметь методы с одинаковыми именами, и это будет унифицировано и возможно удобнее

2023-05-26 13:32 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/item/model/Item.java
>  package ru.practicum.shareit.item.model;
по поводу пакетов я уже писал выше

2023-05-26 15:25 UTC, BerezinYaroslav commented on src/main/java/ru/practicum/shareit/booking/model/Booking.java
> +//enum Status {
есть

2023-05-26 21:41 UTC, BerezinYaroslav commented on src/main/java/ru/practicum/shareit/item/ItemMapper.java
> +    public static ItemDto toItemDto(Item item) {
есть

2023-05-26 21:42 UTC, BerezinYaroslav commented on src/main/java/ru/practicum/shareit/booking/model/Booking.java
> +package ru.practicum.shareit.booking.model;
есть

2023-05-26 21:42 UTC, BerezinYaroslav commented on src/main/java/ru/practicum/shareit/item/model/Item.java
>  package ru.practicum.shareit.item.model;
есть

2023-05-28 09:45 UTC, TomattmanYandex approved these changes
Принято

2023-05-29 14:04 UTC, merged