тз 14
BerezinYaroslav/java-shareit pull request #2
Opened 2023-06-16 21:13 UTC by BerezinYaroslav

2023-06-18 10:12 UTC, TomattmanYandex approved these changes
Привет, отличная работа, нужно пара исправлений

2023-06-18 10:12 UTC, TomattmanYandex commented on pom.xml
> +		<dependency>
а зачем тут эта библиотека если ты ее не используешь

2023-06-18 10:12 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +        if (id == item.getOwner().getId().longValue()) {
iв это обьект, их мы сравниваем через equals

2023-06-18 10:12 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +            Item item = itemRepository.findById(booking.getItem().getId()).orElseThrow();
а зачем мы получаем item а потом сразу его сохраняем

2023-06-18 10:12 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/item/ItemRepository.java
> +    Collection<Item> findByNameOrDescriptionAvailable(String text);
я бы переименовал этот метод findByNameOrDescriptionAndAvailable
потому что сейчас кажется по названию что ищется где доступный дескрипшн

2023-06-18 10:12 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +                    .findByItemId(itemDto.getId(), Sort.by(Sort.Direction.DESC, "start"))
можно было бы сделать метод который ищет только один предыдущий букинг, и один следующий, и использовать их тут, вместо того чтобы получать все букинги для итема а потом фильтровать

2023-06-18 16:31 UTC, BerezinYaroslav commented on pom.xml
> +		<dependency>
есть

2023-06-18 16:38 UTC, BerezinYaroslav commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +        if (id == item.getOwner().getId().longValue()) {
есть

2023-06-18 16:39 UTC, BerezinYaroslav commented on src/main/java/ru/practicum/shareit/item/ItemRepository.java
> +    Collection<Item> findByNameOrDescriptionAvailable(String text);
есть

2023-06-18 16:49 UTC, BerezinYaroslav commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +            Item item = itemRepository.findById(booking.getItem().getId()).orElseThrow();
есть

2023-06-18 19:37 UTC, BerezinYaroslav commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +                    .findByItemId(itemDto.getId(), Sort.by(Sort.Direction.DESC, "start"))
есть

2023-06-19 08:06 UTC, TomattmanYandex requested changes
Привет, один момент еще стоит поправить

2023-06-19 08:06 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +    private BookingItemDto findLastBooking(ItemDto itemDto) {
тут я имел ввиду немного другое, создать метод в репозитории который будет искать предыдущий букинг и следующий букинг, а не сделать все то же самое но в отдельном методе)))

2023-06-19 08:06 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +    private BookingItemDto findLastBooking(ItemDto itemDto) {
сделать запрос, который будет искать букинг (один) по итему и где время меньше переданного, с сортировкой по времени и чтобы возвращал максимум одну запись
и такой же запрос но где дата будет больше переданного

2023-06-19 21:09 UTC, BerezinYaroslav commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +    private BookingItemDto findLastBooking(ItemDto itemDto) {
есть ))) сорян, тупанул

2023-06-20 10:16 UTC, TomattmanYandex approved these changes
Принято

2023-06-20 10:16 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +                            Status.APPROVED)
А нужен ли в методе репозитория статус, если в обоих местах использования он один и тот же, но в принципе универсальный метод, окок

2023-06-20 15:55 UTC, BerezinYaroslav commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +                            Status.APPROVED)
а вдруг потом понадобится расширять)

2023-06-20 15:55 UTC, merged