тз15
BerezinYaroslav/java-shareit pull request #3
Opened 2023-06-27 21:22 UTC by BerezinYaroslav

2023-06-28 11:17 UTC, TomattmanYandex requested changes
Привет, работа хорошая, но не хватает юнит тестов + коменты в коде

2023-06-28 11:17 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +                                                @RequestParam(defaultValue = "10") @PositiveOrZero int size) throws ValidationException {
кажется не очень уместна валидация @PositiveOrZero ведь если будет 0 то будет ошибка

2023-06-28 11:17 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +                                                @RequestParam(defaultValue = "10") @PositiveOrZero int size) throws ValidationException {
и почему в одном месте валидациия есть, в другом нету,  и зачем проверка на уровне сервиса тех же данных

2023-06-28 11:17 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +        if (id == item.getOwner().getId().longValue()) {
объекты сравниваем через equals

2023-06-28 11:17 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +        if (from < 0 || size < 0) {
что будет если size == 0

2023-06-28 11:17 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/item/ItemRepository.java
> +    List<Item> findAllByRequestId(Long requestId);
а разве может быть один реквест на несколько итемов

2023-06-28 11:17 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +        if (from < 0 || size < 0) {
аналогично про size = 0

2023-06-28 11:17 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/request/ItemRequestRepository.java
> +    Page<ItemRequest> findByRequestor_id(Long id, Pageable pageable);
Зачем нижнее подчеркивание, выглядит очень не джавошно

2023-06-28 11:17 UTC, TomattmanYandex commented on src/test/java/ru/practicum/shareit/booking/BookingRepositoryIntegrationTests.java
> +    public void testFindAllByBookerId() {
обычно тестовые методы называют по другому
название метода, что должны делать, при каких условиях, слово тест вообщелишнее, что это тест можно понять по аннотации , но если хочется добавить, то Test добавляют в конце метода
findAllByBookerIdTest так гораздо лучше, потому что сразу видно тестируемы метод, и не надо пропускать test при чтении каждого тестоого метода

2023-06-28 11:17 UTC, TomattmanYandex commented on src/test/java/ru/practicum/shareit/booking/BookingServiceImplTests.java
> +    void addBooking() throws ValidationException {
не надо смешивать тесты кучи разных методов в одном
тестируем метод addBooking следовательно все что надо сделать, это создать букинг через сервис, получить его через репозиторий и после чего сверить поля
именно поэтому мы и именуем так методы, чтобы один конкретный тестовый метод, отвечал за одну небольшую часть функционала

2023-06-28 11:17 UTC, TomattmanYandex commented on src/test/java/ru/practicum/shareit/booking/BookingServiceImplTests.java
> +    private User user;
не понимаю это жедание создать в тесте переменную класса
обычно если для теста нужны какие то данные, их да создают заранее, но в переменные не выносят
а если переменная нужна для сверки, то обьект создают либо в самом тетсте, и тогда есть локальная переменная, либо используют константные значения для сравнения

2023-06-28 21:15 UTC, BerezinYaroslav commented on src/test/java/ru/practicum/shareit/booking/BookingServiceImplTests.java
> +    private User user;
так я в beforeEach их инициализирую и потом в каждом тесте к ним обращаюсь, для этого по факту и объявляю вне методов

2023-06-28 21:22 UTC, BerezinYaroslav commented on src/test/java/ru/practicum/shareit/booking/BookingRepositoryIntegrationTests.java
> +    public void testFindAllByBookerId() {
есть

2023-06-28 21:23 UTC, BerezinYaroslav commented on src/test/java/ru/practicum/shareit/booking/BookingServiceImplTests.java
> +    void addBooking() throws ValidationException {
есть

2023-06-28 21:32 UTC, BerezinYaroslav commented on src/main/java/ru/practicum/shareit/request/ItemRequestRepository.java
> +    Page<ItemRequest> findByRequestor_id(Long id, Pageable pageable);
есть

2023-06-28 21:34 UTC, BerezinYaroslav commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +        if (from < 0 || size < 0) {
есть

2023-06-28 21:35 UTC, BerezinYaroslav commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +        if (id == item.getOwner().getId().longValue()) {
есть

2023-06-28 21:36 UTC, BerezinYaroslav commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +        if (from < 0 || size < 0) {
есть

2023-06-28 21:38 UTC, BerezinYaroslav commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +                                                @RequestParam(defaultValue = "10") @PositiveOrZero int size) throws ValidationException {
есть, пусть будет, как и везде, только на уровне сервиса

2023-06-29 06:59 UTC, BerezinYaroslav commented on src/test/java/ru/practicum/shareit/booking/BookingServiceImplTests.java
> +    void addBooking() throws ValidationException {
есть

2023-06-29 07:11 UTC, BerezinYaroslav commented on src/main/java/ru/practicum/shareit/item/ItemRepository.java
> +    List<Item> findAllByRequestId(Long requestId);
в тз, вроде как, на этом внимание не заостряется, по крайней мере, я перечитал и не нашел. Может, лучше оставить так, чтобы поддерживалось сразу два варианта использования с 1-1 и 1-m

2023-06-29 21:55 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/item/ItemRepository.java
> +    List<Item> findAllByRequestId(Long requestId);
не совсем логично, но не критично

2023-06-29 21:59 UTC, TomattmanYandex requested changes
ПРивет, по тому что есть все отлично, не хватает юнит тестов
Это тесты сервиса, с замоканными другими компонентами, стоит проверить методы где есть какая ни будь внутренняя логика (только на уровне сервиса)

2023-07-03 08:00 UTC, TomattmanYandex requested changes
с тестами еще надо поработать

2023-07-03 08:00 UTC, TomattmanYandex commented on src/test/java/ru/practicum/shareit/booking/MockBookingServiceImplTest.java
> +    private final BookingService service;
ойой, совсем не то, эти тесты не имеют никакого смысла
мокаются обычно зависимости, т.е. мокаем репозитории, и ответ на вызовы методов из него
Наример getAllBookingByState там в зависимости от переданного state вызываются разные методы из репозитория, и можно сделать тест который будет проверять, что при определенном параметре, конкретный метод будет вызван один раз
Или второй вараинт что можно протетсить, это то, что пробрасывается ошибка если пользователь не существует, или предмет не доступен, в первом случае мокаем, что userRepostiry вернет null во втором, что itemRepository вернет item у которого available = false

2023-07-03 08:00 UTC, TomattmanYandex commented on src/test/java/ru/practicum/shareit/booking/MockBookingServiceImplTest.java
> +
А еще лучше переименовать, интеграционный тест так и назвать
BookingServiceImplIntegrationTest или короче BookingServiceImplIT
а юнит тест либо просто
BookingServiceImplTest
либо 
BookingServiceImplUnitTest

2023-07-03 09:51 UTC, BerezinYaroslav commented on src/test/java/ru/practicum/shareit/booking/MockBookingServiceImplTest.java
> +
есть

2023-07-03 09:52 UTC, BerezinYaroslav commented on src/test/java/ru/practicum/shareit/booking/MockBookingServiceImplTest.java
> +    private final BookingService service;
есть

2023-07-04 07:55 UTC, TomattmanYandex approved these changes
Вроде все хорошо, но один момент Интеграционные тесты, это тесты на интеграцию между компоненнтами, а юнит тесты это тесты самих компонентов, поэтому тесты что используют моки, проверяют только сам компонент, а те где реальный репозиторий, это интеграционные, у тебя же наоборот

2023-07-04 08:10 UTC, merged